import { Store } from "../types/types";

// @ts-ignore
export const StoreMock : Store = {
    
    books : [
        // Should be length of 10
        // First item should have key : "OL5901985W"
        {
            "id": 12,
            "key": "OL5901985W",
            "title": "Essays in Honor of Edmond Malinvaud",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL10236835M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": false,
            "tags": ["economy","economics","edmond malinvaud"],
            "authors": "Paul Champsaur",
            "isFavourite": false,
            "pageCount": 590,
            "publishedDate": "1990",
            "created_at": "2024-07-27T05:22:54.000000Z",
        },
        {
            "id": 13,
            "key": "OL158685W",
            "title": "Steget efter",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL26336766M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": true,
            "tags": ["mord","novela","police"],
            "authors": "Henning Mankell",
            "isFavourite": false,
            "pageCount": 537,
            "publishedDate": "1997",
            "created_at": "2024-07-27T05:22:57.000000Z",
        },
        {
            "id": 14,
            "key": "OL137561W",
            "title": "Texaco",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL988784M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": false,
            "tags": ["slavery","history","fiction"],
            "authors": "Patrick Chamoiseau",
            "isFavourite": false,
            "pageCount": 416,
            "publishedDate": "1992",
            "created_at": "2024-07-27T05:23:00.000000Z",
        },
        {
            "id": 15,
            "key": "OL17798838W",
            "title": "Dog Man",
            "imageUrl": null,
            "userId": 2,
            "group": "owned",
            "isRead": true,
            "tags": ["dogs","cats","gatos@","%&^%&^","<b>hello<\/b>"],
            "authors": "Aaron",
            "isFavourite": true,
            "pageCount": 256,
            "publishedDate": "1999",
            "created_at": "2024-07-28T04:06:16.000000Z",
        },
        {
            "id": 19,
            "key": "OL49561W",
            "title": "Shadow of the Giant",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL3312262M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": true,
            "tags": ["novela","fiction","space colonies"],
            "authors": "Orson Scott Card",
            "isFavourite": false,
            "pageCount": 368,
            "publishedDate": "2000",
            "created_at": "2024-07-29T04:02:55.000000Z",
        },
        {
            "id": 20,
            "key": "OL6017238W",
            "title": "The Shock Doctrine",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL13446037M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": false,
            "tags": ["war","guerre","economy"],
            "authors": "Naomi Klein",
            "isFavourite": false,
            "pageCount": 677,
            "publishedDate": "2007",
            "created_at": "2024-07-30T04:43:17.000000Z",
        },
        {
            "id": 21,
            "key": "OL278022W",
            "title": "Freakonomics",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL7280507M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": true,
            "tags": ["economy","humor","finance"],
            "authors": "Steven D. Levitt, Stephen J. Dubner, Andrea Montero Cusset",
            "isFavourite": false,
            "pageCount": 320,
            "publishedDate": "2005",
            "created_at": "2024-07-30T04:43:23.000000Z",
        },
        {
            "id": 22,
            "key": "OL36757475W",
            "title": "New Ideas - the Factor of Global Change",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL49644732M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": true,
            "tags": [],
            "authors": "Alireza Norouzi",
            "isFavourite": false,
            "pageCount": 672,
            "publishedDate": "2018",
            "created_at": "2024-07-30T04:43:33.000000Z",
        },
        {
            "id": 23,
            "key": "OL76827W",
            "title": "The Wealth of Nations",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL38580611M.jpg",
            "userId": 2,
            "group": "wishlist",
            "isRead": true,
            "tags": ["wealth","general","history","economy"],
            "authors": "Adam Smith",
            "isFavourite": false,
            "pageCount": 570,
            "publishedDate": "1776",
            "created_at": "2024-07-30T04:43:42.000000Z",
        },
        {
            "id": 24,
            "key": "OL52456W",
            "title": "Faust",
            "imageUrl": "https:\/\/covers.openlibrary.org\/b\/olid\/OL24206900M.jpg",
            "userId": 2,
            "group": "owned",
            "isRead": true,
            "tags": ["devil","drama","poetry"],
            "authors": "Johann Wolfgang von Goethe",
            "isFavourite": false,
            "pageCount": 306,
            "publishedDate": "1800",
            "created_at": "2024-07-30T04:43:46.000000Z",
        },
    ]
}